### ISSUE TITLE
Repeated phrase - 9.10.1

### ISSUE THREAD

**Issue by julierindone** [LaunchCodeEducation/intro-to-programming-csharp#20]
There is a repeated phrase, which I've tried to bold. There is also an extra word (HEAD) and a missing letter [a] in the first sentence. - maybe a comment gone wrong?

![image](https://user-images.githubusercontent.com/74727813/120685966-14d2ce00-c466-11eb-9437-94a16d01e396.png)

**Comment by speudusa** [comment]
thank you for letting us know!
