### ISSUE TITLE
No right answer 10.4 C.for.U - charstars

### ISSUE THREAD

**Issue by julierindone** [LaunchCodeEducation/intro-to-programming-csharp#25]
![image](https://user-images.githubusercontent.com/74727813/121552476-1fe1ad00-c9d6-11eb-94da-9e56109cb5c4.png)
![image](https://user-images.githubusercontent.com/74727813/121552320-ffb1ee00-c9d5-11eb-8518-e3e17239c95e.png)

**Comment by speudusa** [comment]
thank you for letting us know! this has been updated.
