### ISSUE TITLE
8.3 Swap JS for C#

### ISSUE THREAD

**Issue by julierindone** [LaunchCodeEducation/intro-to-programming-csharp#28]
"As with strings, JavaScript provides us with useful methods for arrays. These methods will either alter an existing array, return information about the array, or create and return a new array."

Should be:
As with strings, **C#** provides us with useful methods for arrays. These methods will either alter an existing array, return information about the array, or create and return a new array.

**Comment by julierindone** [comment]
Also on 8.3: There is a W3Schools link to the JAVASCRIPT array method's page!! Here's a potential substitute: https://www.geeksforgeeks.org/c-sharp-array-class/

**Comment by speudusa** [comment]
thank you for letting us know.  we have updated these links.
